<?php
// print_sales_report.php
// Plain HTML, no JavaScript. Admin prints/saves as PDF via the browser's own Ctrl+P.
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
session_start();
include('../database_connection.php');

//guard rails the file from unauthorize user
if (empty($_SESSION['username']) || $_SESSION['role'] !== 'admin') {
    http_response_code(403);
    exit('Not authorized');
}
$admin_name = $_SESSION['username'];
$date_from = $_GET['date_from'] ?? date('Y-m-01');
$date_to   = $_GET['date_to'] ?? date('Y-m-d');
$status_filter = $_GET['status'] ?? 'all';

$statusClause = "";
$params = [$date_from, $date_to];
$types = "ss";
if ($status_filter !== 'all') {
    // o.order_status (orders table) is the authoritative payment status -
    // op.order_status (order_pending) is a snapshot from order creation and
    // is never updated once payment completes.
    $statusClause = " AND o.order_status = ? ";
    $params[] = $status_filter;
    $types .= "s";
}

$sql = "
    SELECT o.order_date, op.invoice_number, c.first_name, a.username AS artisan_name,
           p.product_name, op.quantity, p.product_price, (op.quantity * p.product_price) AS line_total, o.order_status
    FROM order_pending op
    JOIN products p ON op.product_id = p.product_id
    JOIN orders o ON op.invoice_number = o.invoice_number
    JOIN customers c ON o.customer_id = c.customer_id
    JOIN artisans a ON p.artisan_id = a.artisan_id
    WHERE DATE(o.order_date) BETWEEN ? AND ?
      $statusClause
    ORDER BY o.order_date DESC
";

$stmt = mysqli_prepare($conn, $sql);
mysqli_stmt_bind_param($stmt, $types, ...$params);
mysqli_stmt_execute($stmt);
$result = mysqli_stmt_get_result($stmt);

$rows = [];
$total_revenue = 0;
while ($row = mysqli_fetch_assoc($result)) {
    $rows[] = $row;
    if ($row['order_status'] === 'complete') {
        $total_revenue += $row['line_total'];
    }
}

$customer_count_result = mysqli_query($conn, "SELECT COUNT(*) AS cnt FROM customers");
$total_customers = mysqli_fetch_assoc($customer_count_result)['cnt'];

$artisan_count_result = mysqli_query($conn, "SELECT COUNT(*) AS cnt FROM artisans");
$total_artisans = mysqli_fetch_assoc($artisan_count_result)['cnt'];
?>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>System Sales Report</title>
<style>
    body { font-family: Arial, sans-serif; color: #222; padding: 30px; }
    h1 { margin-bottom: 0; }
    .meta { color: #555; margin-bottom: 20px; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th, td { border: 1px solid #ccc; padding: 8px; text-align: left; font-size: 13px; }
    th { background: #f0f0f0; }
    .total { font-weight: bold; margin-top: 15px; text-align: right; }
    .print-btn{ margin-bottom: 20px; padding: 8px 16px; background:#0E4D3C; color:white; border:none; border-radius:4px; cursor:pointer; }
    .back-link{ margin-bottom: 20px; margin-left: 10px; padding: 8px 16px; background:#eef1f4; color:#1c2b3a; border:none; border-radius:4px; text-decoration:none; display:inline-block; font-family: inherit; font-size: 14px; }
    @media print {
        .print-btn{ display:none; }
        .back-link{ display:none; }
    }
</style>
</head>
<body>
    <button class="print-btn" onclick="window.print()">Print this report</button>
    <a href="index.php" class="back-link">&larr; Back to dashboard</a>
    <h1>ArtisanOrders — System Sales Report</h1>
    <p class="meta">Generated by: <?= htmlspecialchars($admin_name) ?> | Period: <?= htmlspecialchars($date_from) ?> to <?= htmlspecialchars($date_to) ?> | Status: <?= htmlspecialchars($status_filter) ?></p>
    <p class="meta">Total Customers: <?= $total_customers ?> | Total Artisans: <?= $total_artisans ?></p>

    <table>
        <tr><th>Date</th><th>Invoice #</th><th>Customer</th><th>Artisan</th><th>Product</th><th>Qty</th><th>Unit Price</th><th>Line Total</th><th>Status</th></tr>
        <?php foreach ($rows as $r): ?>
        <tr>
            <td><?= htmlspecialchars($r['order_date']) ?></td>
            <td><?= htmlspecialchars($r['invoice_number']) ?></td>
            <td><?= htmlspecialchars($r['first_name']) ?></td>
            <td><?= htmlspecialchars($r['artisan_name']) ?></td>
            <td><?= htmlspecialchars($r['product_name']) ?></td>
            <td><?= (int)$r['quantity'] ?></td>
            <td>KSh <?= number_format($r['product_price'], 2) ?></td>
            <td>KSh <?= number_format($r['line_total'], 2) ?></td>
            <td><?= htmlspecialchars($r['order_status']) ?></td>
        </tr>
        <?php endforeach; ?>
    </table>
    <p class="total">Total Revenue: KSh <?= number_format($total_revenue, 2) ?></p>
</body>
</html>